### ISSUE TITLE
Reports page api updates

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1305]
The reports page needs to be driven by all available questionnaire data. There will also be a dropdown to select which archetype to drive the reports data from at the top of the page with the default being all existing questionnaires in the database with a "required" flag set to true

https://www.sketch.com/s/af50e991-8061-4b69-84c1-c11241e274f2/a/VEvWnDo

https://www.sketch.com/s/af50e991-8061-4b69-84c1-c11241e274f2/a/zyq8Y1M

To do:
  - Current Landscape:
    - [x] Add dropdown to select a questionnaire: See #1374
    - [x] Adjust the donut charts to display aggregated risk when "All questionnaires" is selected: See #1395
    - [x] Adjust the donut charts to display aggregated risk, with `riskMessages` from the questionnaire displayed as a sub-title, when a single questionnaire is selected: See See #1395
  - Identified risks:
    - [ ] rearrange to accommodate Rationale and Mitigation strategies data as expandable rows

**Comment by sjd78** [comment]
Enhancement document section: https://github.com/konveyor/enhancements/blob/90b827b68cc367284a66bf66f087d5c263487e05/enhancements/assessment-module/README.md#changes-in-the-application-reports-view

**Comment by sjd78** [comment]
With the details on this issue a bit old now, and direction changing slightly in advance of the next set of changes, this issue can be closed.
